In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [5]:
b=np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [6]:
d=np.ones((2,2))
print(d)

[[1. 1.]
 [1. 1.]]


In [10]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=a+b
print(c)

[5 7 9]


In [9]:
a=np.array([[1,2],[3,4]])
e=np.array([[5,6],[7,8]])
f=d*e
print(f)

[[5. 6.]
 [7. 8.]]


In [11]:
g=np.array([[1,2],[3,4]])
h=np.array([[5,6],[7,8]])
i=np.dot(g,h)
print(i)

[[19 22]
 [43 50]]
